#+BEGIN_COMMENT
.. title: Research
.. slug: research
.. date: 2018-03-25 21:38:43 UTC-04:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


* Ammonia Synthesis using Plasma-enabled Catalysis

Ammonia, a precursor to fertilizer, is responsible for feeding a large fraction of the global population. Industrially, ammonia is manufactured by the chemical transformation of nitrogen and hydrogen gases via the Haber-Bosch process. The process typically carried out on the surfaces of solid materials known as catalysts. Even with the best-known catalysts, the process is very energy intensive, and requires very high pressures (100-200 atm) and temperatures (700-800 K) for it to be feasible. Reducing these temperature and pressure requirements are a grand challenge for sustainable ammonia synthesis.

The central idea behind this research is to assist conventional catalysts (metal nanoparticles on metal oxide supports) by applying an electric discharge (also referred to as a non-thermal plasma). Our hypothesis is the plasma can selectively activate the strong triple bond of the nitrogen molecule by vibrational excitation in a way that is not possible by thermal heating in conventional catalysis. In work completed so far, I have developed a computational model based on quantum mechanical density functional theory (DFT) calculations that incorporates the effect of nitrogen vibrational excitation and knowledge of thermal catalysis. Two key insights emerge from this model. The first is that ammonia synthesis rates in the presence of the plasma are expected to be greatly enhanced over thermal rates for a given bulk temperature and pressure. Second, the optimal catalyst materials and active sites in the presence of plasma excitation may not be the same as those for thermal catalysis. Experimental rate measurements by our collaborators confirm that ammonia is produced over metal catalysts at conditions far removed from Haber-Bosch, and the relative trends in activity are found to be consistent with the predicted trends. This work is among the first examples of the computationally guided design of plasma-catalyst systems, and has been accepted for publication in the journal Nature Catalysis.

*Related Publications*

- P.Mehta, P.Barboun, F.Herrera, J.Kim, P.Rumbach, D.B.Go, J.C.Hicks, W.F. Schneider. Overcoming Ammonia Synthesis Scaling Relations with Plasma-enabled Catalysis. Nature Catalysis, 2018, accepted. [[https://doi.org/10.1038/s41929-018-0045-1][DOI: 10.1038/s41929-018-0045-1]]  [[https://zenodo.org/record/1171213#.WrhZjmaZPUI][supporting dataset]]

*Related Poster*




* Accurate Free Energy Models in Catalysis

* Computational Modeling of Catalytic Interfaces
